// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/israelalvesmelo/di/product"
)

// Injectors from wire.go:

func NewUseCase(db *sql.DB) *product.ProductUsecase {
	productRepository := product.NewProductRepository(db)
	productUsecase := product.NewProductUsecase(productRepository)
	return productUsecase
}
